In [31]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import warnings

In [32]:
fp = "H:/ML Projects/credit_data.csv"
data = pd.read_csv(fp , sep=",")

In [33]:
"To get unique categories for various columns"

for col in data:
    print(data[col].unique())

[19 18 29 26 28 24 21 20 22 27 25 23 30 32 41 38 62 34 63 33 61 46 31 42
 50 39 36 60 37 47 43 51 49 45 44 48 58 35 59 56 40 54 55 57 64 52 53]
['Male' 'Female']
['Graduate' 'Under Graduate' 'Post Graduate' 'Other']
['Professional' 'Salaried' 'Student' 'Business']
['None' 'Tier 3' 'Tier 2' 'Tier 1']
['None' 'Entry' 'Mid-level 1' 'Junior' 'Mid-level 2' 'Senior']
[186319 277022 348676 ... 333840 306053 385157]
[21625 20442 24404 ... 46779 43751 32684]
['Family' 'Rented' 'Company provided' 'Owned']
['None' 'Two Wheeler' 'Four Wheeler']
['Married' 'Single' 'Other']
[0 1 2]
[1 0]


In [34]:
"Map categorical values to float values"

warnings.simplefilter("ignore")

data.gender[data.gender == 'Male'] = 0
data.gender[data.gender == 'Female'] = 1

data.education[data.education == 'Graduate'] = 0
data.education[data.education == 'Under Graduate'] = 1
data.education[data.education == 'Post Graduate'] = 2
data.education[data.education == 'Other'] = 3

data.occupation[data.occupation == 'Professional'] = 0
data.occupation[data.occupation == 'Salaried'] = 1
data.occupation[data.occupation == 'Student'] = 2
data.occupation[data.occupation == 'Business'] = 3

data.organization_type[data.organization_type == 'None'] = 0
data.organization_type[data.organization_type == 'Tier 1'] = 1
data.organization_type[data.organization_type == 'Tier 2'] = 2
data.organization_type[data.organization_type == 'Tier 3'] =3

data.seniority[data.seniority == 'None'] = 0
data.seniority[data.seniority == 'Entry'] = 1
data.seniority[data.seniority == 'Mid-level 1'] = 2
data.seniority[data.seniority == 'Junior'] = 3
data.seniority[data.seniority == 'Mid-level 2'] = 4
data.seniority[data.seniority == 'Senior'] = 5

data.house_type[data.house_type == 'Family'] = 0
data.house_type[data.house_type == 'Rented'] = 1
data.house_type[data.house_type == 'Company provided'] = 2
data.house_type[data.house_type == 'Owned'] = 3

data.vehicle_type[data.vehicle_type == 'None'] = 0
data.vehicle_type[data.vehicle_type == 'Two Wheeler'] = 1
data.vehicle_type[data.vehicle_type == 'Four Wheeler'] = 2

data.marital_status[data.marital_status == 'Single'] = 0
data.marital_status[data.marital_status == 'Married'] = 1
data.marital_status[data.marital_status == 'Other'] = 2

data.head()

age gender education occupation organization_type seniority  annual_income  \
0   19      0         0          0                 0         0         186319   
1   18      0         1          0                 0         0         277022   
2   29      0         1          1                 0         1         348676   
3   18      0         0          2                 0         0         165041   
4   26      0         2          1                 0         2         348745   

   disposable_income house_type vehicle_type marital_status  no_card  default  
0              21625          0            0              1        0        1  
1              20442          1            0              1        0        1  
2              24404          1            0              1        1        1  
3               2533          1            0              1        0        1  
4              19321          1            0              1        1        1

In [35]:
X = data.iloc[: , 0:11].values
Y = data.iloc[: , 12].values

"Splitting the values to train set and test set"

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

"Define decision tree models with entropy criterion"

model = DecisionTreeClassifier(criterion="entropy", random_state=0, min_samples_leaf=50)

"Fit the models"

model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=50, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [36]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [37]:
"To find the accuracy of the model"

print(accuracy_score(y_test , y_pred)*100)

85.6691462049898
